cart/urls.py
from django.urls import path
from . import views

app_name = "cart"


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('cart_clear/',views.cart_clear , name='cart_clear'),
   
   
    
]

fabtrendapp/urls.py
from django.urls import path
from fabtrendapp import views
from django.contrib.auth import views as auth_views
app_name = "fabtrendapp"

urlpatterns = [

    path('', views.indexpageView.as_view(), name='index'),
    path('base/', views.basepageView.as_view()),
    path('contact/', views.contactpageView.as_view(), name='contact'),
    path('checkout/', views.checkoutpageView.as_view(), name='checkout'),
    path('privacy/', views.privacypageView.as_view(), name='privacy'),
    path('addproduct/', views.addproductpageview.as_view()),
    path('FAQs/', views.FAQspageView.as_view(), name='faqs'),
    path('about/', views.aboutpageView.as_view(), name='about'),
    path('delete/<int:id>', views.destroy),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('insert/', views.insert),
    path('list/', views.listView.as_view()),
    path('product/', views.product, name='product'),
    path('search/', views.search, name='search'),
    path('email_success/', views.email_success, name='email_success'),
    path('category/', views.CategoryListView.as_view(), name='categorylist'),
    path('subcategory/', views.SubcategoryListView.as_view(), name='subcategorylist'),
    path('product/', views.productpageView.as_view()),
    path('product/<int:cat>/', views.show),
    path('insertproduct/', views.insertproduct,name="insertproduct"),
    path('products/<int:myid>', views.productView, name="productView"),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('query/', views.querypageview.as_view(),name='query'),
    path('feedback',views.Feedbackpageview.as_view(),name="feedback"),
	path('insertfeedback',views.feedback),
    path('feedbacks/',views.FeedbacklistView.as_view(),name="feedbacks"),
    path('insertquery/',views.insertquery),
    path('home/',views. account_home_page, name='account-home'),
    path('all_products/', views.all_products , name='all_products'),
]

fabtrendshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers, serializers, viewsets


urlpatterns = [
                path('admin/', admin.site.urls),
                path('', include('fabtrendapp.urls')),
                path('cart/', include('cart.urls')),
                path('orders/', include('orders.urls')),
                path('paytm/', include(('paytm.urls','paytm'),namespace='paytm')),
                path('coupons/', include(('coupons.urls','coupons'),namespace='coupons')),
                path('wishlists/', include(('wishlists.urls','wishlists'),namespace='wishlists')),
        ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wishlists/urls.py
from django.urls import path
from . import views



app_name = 'wishlists'

urlpatterns = [
    path('<int:product_id>/add/', views.add_wishlist , name='add_wishlist'),
    path('my_wishlists/', views.my_wishlists , name='my_wishlists'),
    path('clear_wishlists/', views.clear_wishlists , name='clear_wishlists'),
    path('<int:product_id>/delete_wishlist/', views.delete_wishlist , name='delete_wishlist'),
    # path('<int:post_id>/delete/', views.delete_wishlist , name='delete_wishlist'),


]

wishlists/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from datetime import datetime


from fabtrendapp.models import Product
from django.contrib.auth.models import User
# Create your models here.


class WishList(models.Model):
    user_id = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='wishlist_product')

    
    def __str__(self):
        return str(self.product.id)
     
    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * (self.discount / Decimal('100'))
    
    def get_total_price(self):
        return sum(Decimal(item['price']) * item['quantity'] for item in self.cart.values())

wishlists/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from cart.forms import CartAddProductForm
from fabtrendapp.models import Product
from wishlists.models import WishList
from django.contrib import auth, messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, AuthenticationForm
from django.core.mail import send_mail, BadHeaderError
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView

from cart.forms import CartAddProductForm
from fabtrendapp.forms import feedbackform, queryform, Productform
from fabtrendapp.models import contact, category, FAQs, Product, subcategory, feedback



def add_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    user_id = request.user.id

    wl = WishList(user_id=user_id, product=product)
    wl.save()
    if wl:
        messages.success(request, 'WishLists Created SuccessFully')
        return redirect('/')
    else:
        messages.warning(request, 'SomeThing Went Wrong')
        return redirect('/')


def my_wishlists(request):
    products = WishList.objects.filter(user_id=request.user.id).select_related('product')
   
    wishlists = []
    
    for i in products:
        i = str(i)
        product = Product.objects.get(pk=i)
        wishlists.append(product)
    cart_product_form = CartAddProductForm()
    context = {
        'title': 'My WishList',
        'wishlists': wishlists,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'wishlists.html', context)


def clear_wishlists(request):
    products = WishList.objects.filter(user_id=request.user.id).select_related('product').delete()
    context = {
        'title': 'My WishList',
    }
    return render(request, 'wishlists.html', context)


def delete_wishlist(request, product_id):
    wl = WishList.objects.get(product=product_id)
    wl.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    
    

wishlists/templates/wishlists.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="row" style="background:rgba(230, 232, 230,0.4);">
<br><br>
        <p style="background:rgba(53,158,128,0.6); color:white;padding:10px;text-align:center;font-size:40px;font-weight:bold;"> Your Wishlist</p>
	</div>
 
 <div class="row"  style="background:rgba(230, 232, 230,0.4);">
 <br><br>
  	<div class="container">
            <table class="table table-bordered" style="background:white;" >
                <thead style="font-family:Arial Rounded MT;color:black;text-align:center;font-size:18px;">
		 <tr style="font-color:white; width:30px !important">
						 <th style="text-align:center;">Remove</th>
                        <th  style="text-align:center;">Image</th>
                        <th  style="text-align:center;">Product Name</th>
                        <th  style="text-align:center;">Unit Price</th>
                        
                        <th  style="text-align:center;">Add to Cart</th>
						
                       
                    </tr>
                </thead>
                <tbody>
				 
		{% for value in wishlists %}
		 
			        <tr><td  style="text-align:center;"><a href="{% url "wishlists:delete_wishlist" value.id %}"><i class="fa fa-trash" aria-hidden="true" style="color:rgb(53,158,128);font-size:40px;margin-top:30px;"></i></a></td>
					<td  style="text-align:center;"><img src="/media/{{ value.image}}" alt="..." style="height:120px; width:120px;"></td>
                            <td  style="text-align:center;padding-top:30px;font-family:Arial Rounded MT;">{{ value.name }}</td>
                        <td  style="text-align:center;padding-top:30px;font-family:Arial Rounded MT;">Rs. {{ value.price }}</td>
						
			<form action="{% url "cart:cart_add" value.id %}" method="post">
                                    {% csrf_token %}
                                  
                                  <td  style="text-align:center;margin-top:30px;"> <input  style="text-align:center;margin-top:30px;" type="submit" value="Add to cart" class="cartbutton1"></td>
								  {{ cart_product_form }}
</form>  
						
	 </tr>
                {% endfor %}
</tbody>
		</table>
		
		 <a href="{% url "wishlists:clear_wishlists" %}" class="btn btn-info"  style="float:right;margin-bottom:30px;margin-left:10px;" >Clear wishlists</a>
		 <a href="{% url "fabtrendapp:index" %}" style="float:right;" class="btn btn-info" id="cartbutton1">Continue Shopping</a>
	</div>		
	</div>		

 
{% endblock %}