cart/urls.py
from django.urls import path
from . import views

app_name = "cart"


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('cart_clear/',views.cart_clear , name='cart_clear'),
   
   
    
]

fabtrendapp/urls.py
from django.urls import path
from fabtrendapp import views
from django.contrib.auth import views as auth_views
app_name = "fabtrendapp"

urlpatterns = [

    path('', views.indexpageView.as_view(), name='index'),
    path('base/', views.basepageView.as_view()),
    path('contact/', views.contactpageView.as_view(), name='contact'),
    path('checkout/', views.checkoutpageView.as_view(), name='checkout'),
    path('privacy/', views.privacypageView.as_view(), name='privacy'),
    path('addproduct/', views.addproductpageview.as_view()),
    path('FAQs/', views.FAQspageView.as_view(), name='faqs'),
    path('about/', views.aboutpageView.as_view(), name='about'),
    path('delete/<int:id>', views.destroy),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('insert/', views.insert),
    path('list/', views.listView.as_view()),
    path('product/', views.product, name='product'),
    path('search/', views.search, name='search'),
    path('email_success/', views.email_success, name='email_success'),
    path('category/', views.CategoryListView.as_view(), name='categorylist'),
    path('subcategory/', views.SubcategoryListView.as_view(), name='subcategorylist'),
    path('product/', views.productpageView.as_view()),
    path('product/<int:cat>/', views.show),
    path('insertproduct/', views.insertproduct,name="insertproduct"),
    path('products/<int:myid>', views.productView, name="productView"),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('query/', views.querypageview.as_view(),name='query'),
    path('feedback',views.Feedbackpageview.as_view(),name="feedback"),
	path('insertfeedback',views.feedback),
    path('feedbacks/',views.FeedbacklistView.as_view(),name="feedbacks"),
    path('insertquery/',views.insertquery),
    path('home/',views. account_home_page, name='account-home'),
    path('all_products/', views.all_products , name='all_products'),
]

fabtrendshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers, serializers, viewsets


urlpatterns = [
                path('admin/', admin.site.urls),
                path('', include('fabtrendapp.urls')),
                path('cart/', include('cart.urls')),
                path('orders/', include('orders.urls')),
                path('paytm/', include(('paytm.urls','paytm'),namespace='paytm')),
                path('coupons/', include(('coupons.urls','coupons'),namespace='coupons')),
                path('wishlists/', include(('wishlists.urls','wishlists'),namespace='wishlists')),
        ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, include
app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^created/$', views.order_created, name='order_created'),
    #url(r'^my_orders/$', views.my_orders, name='my_orders'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('refund-request/', views.RequestRefundView.as_view(), name='refund-view'),
]

wishlists/urls.py
from django.urls import path
from . import views



app_name = 'wishlists'

urlpatterns = [
    path('<int:product_id>/add/', views.add_wishlist , name='add_wishlist'),
    path('my_wishlists/', views.my_wishlists , name='my_wishlists'),
    path('clear_wishlists/', views.clear_wishlists , name='clear_wishlists'),
    path('<int:product_id>/delete_wishlist/', views.delete_wishlist , name='delete_wishlist'),
    # path('<int:post_id>/delete/', views.delete_wishlist , name='delete_wishlist'),


]

fabtrendapp/views.py
from django.contrib import auth, messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, AuthenticationForm
from django.core.mail import send_mail, BadHeaderError
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, View
from django.core.paginator import Paginator
from cart.forms import CartAddProductForm
from fabtrendapp.forms import feedbackform, queryform, Productform
from fabtrendapp.models import contact, category, FAQs, Product, subcategory, feedback
from .forms import SignUpForm, EditProfileForm,  contactform
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.http import HttpResponse


class indexpageView(TemplateView):
    template_name = "index.html"


class basepageView(TemplateView):
    template_name = "base.html"


class contactpageView(TemplateView):
    template_name = "contact.html"


class checkoutpageView(TemplateView):
    template_name = "checkout.html"


class belliespageView(TemplateView):
    template_name = "bellies.html"


class privacypageView(TemplateView):
    template_name = "privacy.html"


class aboutpageView(TemplateView):
    template_name = "about.html"


class editView(TemplateView):
    template_name = "edit.html"


class productpageView(TemplateView):
    template_name = "product.html"


class addproductpageview(TemplateView):
    template_name = "addproduct.html"


class basepageView(TemplateView):
    template_name = "base.html"


class FAQspageView(ListView):
    template_name = "FAQs.html"

    def get_queryset(self):
        return FAQs.objects.all()


class feedbackpageview(TemplateView):
    template_name = "feedback.html"


class querypageview(TemplateView):
    template_name = "query.html"


class listView(ListView):
    template_name = "list.html"

    def get_queryset(self):
        return contact.objects.all()


class Feedbackpageview(TemplateView):
    template_name = "feedback.html"


class FeedbacklistView(ListView):
    template_name = "feedbacklist.html"

    def get_queryset(self):
        return feedback.objects.all()


def post(self, request, text):
    form = contactform(request.POST)
    if form.is_valid():
        form.save()
        text = form.cleaned_data['name']
        text = form.cleaned_data['phoneno']
        text = form.cleaned_data['email']
        text = form.cleaned_data['address']
        form = contactform()
        messages.add_message(request, messages.INFO, 'Submitted.')
        return redirect('/contact')
    args = {'form': form, 'text': text}
    return render(request, self.template_name, args)


def insert(request):
    if request.method == "GET":
        form = contactForm()
    else:
        form = contactform(request.POST, request.FILES)
        name = request.POST.get('name')
        phoneno = request.POST.get('phoneno')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        if form.is_valid():
            name = request.POST.get('name')
            phoneno = request.POST.get('phoneno')
            email = request.POST.get('email')
            subject = request.POST.get('subject')
            message = request.POST.get('message')
            try:
                form.save()
                send_mail(subject, message, email, ['jashanmakkar62@gmail.com'], name)
                messages.add_message(request, messages.INFO, 'Submitted.')
                return redirect('/email_success')
            except BadHeaderError:
                return HttpResponse('Invalid Header Found')
            return redirect('/email_success')
        else:
            form = contactform()
        return render(request, 'contact.html', {'form': form})


def email_success(request):
    context = {}
    template = 'email_success.html'
    return render(request, template, context)


def edit(request, id):
    con = contact.objects.get(id=id)
    return render(request, 'edit.html', {'con': con})


def update(request, id):
    con = contact.objects.get(id=id)
    form = contactform(request.POST, instance=con)
    if form.is_valid():
        form.save()
        return redirect("/contact")
    return render(request, 'edit.html', {'con': con})


def destroy(request, id):
    con = contact.objects.get(id=id)
    con.delete()
    return redirect("/")


def insertproduct(request):
    if request.method == "POST":
        form = Productform(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()
                return redirect('/insertproduct/')
            except:
                pass
    else:
        form = Productform()
    return render(request, 'addproduct.html', {'form': form})


class CategoryListView(ListView):
    model = category
    template_name = "category.html"


class SubcategoryListView(ListView):
    model = subcategory
    template_name = "subcategory.html"


class ProductListView(object):
    pass


def show(request, cat):
    pro = Product.objects.filter(subcategory=cat)
    subcat = subcategory.objects.get(id=cat)
    cart_product_form = CartAddProductForm()
    context = {
        'pro': pro,
        'subcat': subcat,
        'cart_product_form': cart_product_form
    }
    return render(request, "product.html", context)


def header(request):
    category_list = category.objects.all()
    context_dict = {'cat': category_list, }
    return render(request, 'base.html', context_dict)

def product(request):
    products = Product.objects.all()
    paginate_by = 10
    context = {
        'products': products,
    }
    return render(request, 'product.html', context)

@login_required(login_url='/login/')
def productView(request, myid):
    products = Product.objects.filter(id=myid)
    product = Product.objects.get(id=myid)
    cart_product_form = CartAddProductForm()

    context = {
        'products': products,
        'product': product,
        'cart_product_form': cart_product_form,
    }
    return render(request, "productview.html", context)


def search(request):
    global cart_product_form
    produ = None
    query = None
    if 'q' in request.GET and request.GET['q']:
        query = request.GET.get('q')
        produ = Product.objects.all().filter(Q(name__icontains=query) | Q(description__icontains=query))
        cart_product_form = CartAddProductForm()
    else:
        produ = Product.objects.order_by('published_on')
    return render(request, 'search.html', {'query': query, 'produ': produ, 'cart_product_form': cart_product_form})


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            user = auth.authenticate(username=username, password=raw_password)
            if user is not None:
                auth.login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                if 'next' in request.POST:
                    return HttpResponseRedirect(request.POST['next'])
                else:
                    return HttpResponseRedirect('/')
                return redirect('/')
            else:
                messages.success(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
            return render(request, 'registration/login.html')
    form = AuthenticationForm()
    return render(request=request,
                  template_name="registration/login.html",
                  context={"form": form})


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            raw_password = form.cleaned_data['password1']
            user = auth.authenticate(username=username, password=raw_password)
            auth.login(request, user)
            messages.info(request, f" Dear {username}!, You are registered in fabtrends")
            return redirect('/')
    else:
        form = SignUpForm()

    context = {'form': form}
    return render(request, 'registration/sign.html', context)


def logout(request):
    auth.logout(request)
    messages.success(request, 'Youre now logged out')
    return redirect('/')


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'You have edited your profile')
            return redirect('/')
    else:  # passes in user information
        form = EditProfileForm(instance=request.user)

    context = {'form': form}
    return render(request, 'registration/edit_profile.html', context)


# return render(request, 'authenticate/edit_profile.html',{})

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'You have edited your password')
            return redirect('/')
    else:  # passes in user information
        form = PasswordChangeForm(user=request.user)

    context = {'form': form}
    return render(request, 'registration/change_password.html', context)


class feedbackpageview(TemplateView):
    template_name = "feedback.html"

@login_required
def feedback(request):
    if request.method == 'POST':

fabtrendapp/templates/all_products.html
{% extends "base.html" %}

{% block title %}
    {{title}}
{% endblock title %}



{% block content %}

<div class="row" id="product">
  {% for p in products %}
  
	 <div class=" col-md-3">
							<div class="agile_ecommerce_tab_left dresses_grid">
							<div class="thumbnail">
								<div class="hs-wrapper hs-wrapper2" style="width:100%;height:100%;">
									<img src="/media/{{ p.image }}" alt=" " class="img-responsive"/>
									<img src="/media/{{ p.image1 }}" alt=" " class="img-responsive"/>
									<img src="/media/{{ p.image2 }}" alt=" " class="img-responsive"/>
									<img src="/media/{{ p.image3 }}" alt=" " class="img-responsive"/>
									<img src="/media/{{ p.image4 }}" alt=" " class="img-responsive"/>
								</div>
								<h5 id="productname">{{ p.name }}</h5>
								<div class="simpleCart_shelfItem">
									<p><i class="item_price productprice">Rs. {{ p.price }}</i><span class="productprice">Rs. {{ p.discounted_price }} </span> </p>
									<form action='{% url "cart:cart_add" p.id %}' method="post">
	{% csrf_token %}
	<div class="cart">
	{{ cart_product_form }}
	<a><input type="submit" value="Add to cart" class="cartbutton1"></a>
	</div>
</form>
<form action='{% url "fabtrendapp:productView" p.id %}' method="post" style="margin-top:0;">
	{% csrf_token %}
	{{ fabtrendapp_productview_form }}
<a href="/fabtrendapp/products/{{p.id}}" style="margin-top:10px;"><input type="submit" class="cartbutton3" value="QuickView" id="qv{{p.id}}"></a>
</form>


								</div>
								<div class="dresses_grid_pos">
									<h6 style="text-align:center">{{ p.tag }}</h6>
								 <br>
								 <br>
								 <br>
								 <br>
								 <br>
								 <br>
								 <br>
								 <br>
								 <br>
								 <br>
								 <br>
								
								  <a  style="margin-left:50px;"href="{% url "wishlists:add_wishlist" p.id %}"><i  style="font-size:25px;padding-right:10px !important;color:rgb(58,151,128);"class="fa fa-heart"></i></a>
								</div>
								
								
								
				</div>
							</div>
</div>							
  {% endfor %}
</div>
<div class="row">
<div class="container" style="text-align:center;color:rgb(53,151,128);">
       <div class="mx-auto mt-4 clearfix">

          {% if products.has_other_pages %}

            <ul class="pagination">
               {% if products.has_previous %}
                  <li class="page-item" >
                    <a href="?page={{products.previous_page_number}}" class="page-link">&laquo;</a>
                  </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link">&laquo;</a>
                   </li>
               {% endif %}
               {% for i in products.paginator.page_range %}
                 {% if products.number == i %}

                  <li class="page-item active">
                    <a class="page-link">{{i}}</a>
                  </li>
                 {% else %}
                      <li class="page-item">
                        <a href="?page={{i}}" style="text-align:center;color:rgb(53,151,128);" class="page-link">{{i}}</a>
                      </li>
                 {% endif %}
               {% endfor %}
               {% if products.has_next %}
                  <li class="page-item">
                    <a href="?page={{products.next_page_number}}" class="page-link">&raquo;</a>
                  </li>
               {% else %}
                   <li class="page-item disabled">
                      <a class="page-link">&raquo;</a>
                   </li>
               {% endif %}
            </ul>

          {% else %}

          {% endif %}

  </div>
  </div>
  </div>



{% endblock content %}

fabtrendapp/templates/base.html
{% load static %}
<html>
<head>
<title>FabTrends Women's Shopping Mart</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="{% static 'images/logo.png' %}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.4.1-dist/css/bootstrap.min.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.4.1-dist/Font-Awesome-master/Font-Awesome-master/css/fontawesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.4.1-dist/Font-Awesome-master/Font-Awesome-master/css/all.css' %}">
<link href="{% static 'style1.css' %}" type="text/css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'slider/JiSlider.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.4.1-dist/flexslider.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.4.1-dist/fasthover.css' %}">
<script src ="{% static 'bootstrap-3.4.1-dist/jquery.js' %}"></script>
<script src ="{% static 'bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>
<script  type= "text/javascript" src= "{% static 'slider/JiSlider.js' %}"></script>
</head>
<body><!--Navbar-->
<!--/.Navbar-->
<a id="buttonstore"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
<!-- Back to top button -->
<!-- begin topbar-->
<div class="container-fluid">
		<div class="row" id="header">
                <div class="col-md-3">
			    <a href="/product/11/" class="btn btn-info" id="button1" style="border:none;">Offer of the day</a>
			</div>
			<div class="col-md-9">
           <nav class="navbar-inverse" id="nav">
			   <ul class="nav navbar-nav" style="background:black;">
			  
{% if user.is_authenticated %}
        <li class="dropdown">
          <a class="nav-link dropdown-toggle nav-item" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i>
            {{request.user.username}}<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
		  <li><a href="{% url 'fabtrendapp:edit_profile' %}" style="color:black !important;"><i class="fa fa-user"
              aria-hidden="true"></i>Edit Profile</a></li> 
			  <li><a href="{% url 'fabtrendapp:change_password' %}" style="color:black !important;"><i class="fa fa-lock"
              aria-hidden="true"></i>Change Password</a></li>
            <li class="nav-item"><a href="{% url "wishlists:my_wishlists"%}" style="color:black !important;"><i class="fa fa-heart"></i>My Wishlist</a></li>
<li class="nav-item"><a href="{% url 'orders:order_create' %}" style="color:black !important;"><i class="fas fa-shopping-basket"></i>Checkout</a></li>
<li class="nav-item"><a href="{% url 'fabtrendapp:feedback' %}" style="color:black !important;"><i class="fas fa-comments"></i>Feedback</a></li>
<li class="nav-item"><a href="{% url 'orders:refund-view' %}" style="color:black !important;"><i class="fa fa-shopping-bag"></i>Refund</a></li>
 <li class="nav-item"><a href="{% url "cart:cart_detail" %}" style="color:black !important;">
	<i class="fas fa-shopping-cart" style="color:black;"></i>Your Cart
	{% with total_items=cart|length %}
                    {% if cart|length > 0 %}
              [{{ total_items }}]
                        {% else %}
                       [0]
                    {% endif %}
                {% endwith %}

       </a></li>    
          </ul>
        </li>
    <li><a class="list" href="{% url 'fabtrendapp:logout' %}"> <i class="fa fa-key" aria-hidden="true"></i>logout</a></li>
{% else %}
<li><a href="{% url 'fabtrendapp:register' %}"><i class="fa fa-user-plus"></i>Signup</a></li>
<li><a href="{% url 'fabtrendapp:login' %}"><i class="fa fa-unlock-alt"></i>Login</a></li>
{% endif %}
				<li class="list"><a href="{% url 'fabtrendapp:about' %}"><i class="fas fa-user-alt"></i>About Us</a></li>
				<li class="list"><a href="{% url 'fabtrendapp:contact' %}"><i class="fas fa-user-tie"></i>Contact Us</a></li>
				
				
				<li class="list"><a href="{% url 'fabtrendapp:query' %}"><i class="fa fa-question-circle"></i>Query</a></li>
				

			    </ul>
			</nav>
		</div>
</div>
<!--end topbar-->

<!--begin topbar-->
<div class="row">
<ul id="navbar">
	<div class="col-md-2">
<a href="{% url 'fabtrendapp:index' %}"><img src="{% static 'images/title2.png' %}" id="img"/></a>
</div>
<div class="col-md-10" id="header1">

	<li> <a href="{% url 'fabtrendapp:index' %}"><span class="home">HOME</span></a></li>
	
	
	{% for category in cat %}
	
	<li class="dropdown">
			<a class="dropbtn" href="#">{{ category }}<i class="fa fa-caret-down" style=""></i></a>
			<div class="dropdown-content">
			{% for subcat in category.subcategory.all %}
			<a href="/product/{{ subcat.id }}">{{ subcat.name }}</a>
			{% endfor %}	
			</div>
		</li>
	{% endfor %}
	
	
	
		<!--<li class="dropdown">
			<a class="dropbtn" href="{% url 'fabtrendapp:categorylist' %}">CLOTHING<i class="fa fa-caret-down" style=""></i></a>
			<div class="dropdown-content">
			<div class="col-md-6">
			<a href="">Kurties</a>
				<a href="">Suits</a>
				<a href="">Dresses</a>
				<a href="">Top & Shirts</a>
				</div>
				<div class="col-md-6">
				<a href="">Trousers</a>
				<a href="">Jeans</a>
				<a href="">Gowns</a>
				<a href="">JumpSuit</a>
				</div>
			</div>
		</li>
		<li class="dropdown">
			<a class="dropbtn" href="{% url 'fabtrendapp:categorylist' %}">FOOTWEAR<i class="fa fa-caret-down" style=""></i></a>
			<div class="dropdown-content">
				<a href="#">Heels</a>
				<a href="#">Wedges</a>
				<a href="#">Ballerinas</a>
				<a href="#">Shoes</a>
				<a href="#">Flip-Flops</a>
				<a href="#">Sandals</a>
			</div>
		</li>
		<li class="dropdown">
			<a class="dropbtn" href="{% url 'fabtrendapp:categorylist' %}">JEWELLERY<i class="fa fa-caret-down" style=""></i></a>
			<div class="dropdown-content">
				<a href="#">Nacklace & sets</a>
				<a href="#">Earrings</a>
				<a href="#">Rings</a>
				<a href="#">Head Jewellery</a>
				<a href="#">Watches</a>
				<a href="#">Bangle Bracelet</a>
			</div>
		</li>
		<li class="dropdown">
			<a class="dropbtn" href="{% url 'fabtrendapp:categorylist' %}">COSMATICES<i class="fa fa-caret-down" style=""></i></a>
			<div class="dropdown-content">
				<a href="#">Eye Makeup</a>
				<a href="#">Face makeup</a>
				<a href="#">Lip Accessory</a>
				<a href="#">Nail Accessory</a>
			</div>
	</li>-->

		<div id="wrap">
		<form action="/search/" autocomplete="on" method="get">
		{% csrf_token %}
  		<input id="search" name="q" type="text" placeholder="What're we looking for ?">
  		<button class="searchButton" value="Rechercher" type="submit"><i class="fas fa-search"></i></button>
  		</form>
		</div>
		
		 <a href="{% url "cart:cart_detail" %}" style="color:white;">
	<button class="cartButton"><i class="fas fa-shopping-cart"></i>{% with total_items=cart|length %}
                    {% if cart|length > 0 %}
              [{{ total_items }}]
                        {% else %}
                       [0]
                    {% endif %}
                {% endwith %}
	</button>
       </a>
</div>
</ul>
</div>

{% block content %}
{% endblock %}



<!--begin footer -->
<div class="row">
	<div class="footer" style="padding-bottom:20px;">
		<div class="container">
				<div class="col-md-3">
					<h4 class="hammer5">Contact</h4>
					<ul class="address">
						<li> Jass Makkar</li>
						<li>Bathinda</li>
						<li>makkar62@gmail.com</li>
						<li>98559-99322</li>
					</ul>
				</div>
				<div class="col-md-3">
					<h4 class="hammer5">Information</h4>
					<ul class="info">
						<li><a href="{% url 'fabtrendapp:about' %}">Contact Us</a></li>
						<li><a href="{% url 'orders:order_create' %}">Checkout</a></li>
					  
						<li><a href="{% url 'fabtrendapp:faqs' %}">FAQs</a></li>
						<li><a href="{% url 'fabtrendapp:privacy' %}">Privacy policy</a></li>
						<li><a href="{% url 'fabtrendapp:about' %}">About</a></li>
						<li><a href="{% url 'fabtrendapp:feedback' %}">Feedback</a></li>
						<li><a href="{% url 'fabtrendapp:query' %}">Query</a></li>
					</ul>
				</div>
				<div class="col-md-3">
					<h4 class="hammer5">Category</h4>
					<ul class="info">
						<li><a href="dresses.aspx">Dresses</a></li>
										<li><a href="/product/1/">Kurtas</a></li>
										<li><a href="/product/5/">Jeans</a></li>
										<li><a href="/product/3/">Top & Shirts</a></li>
                                        <li><a href="/product/6/">Palazoo & leggings</a></li>
                                        <li><a href="/product/26/">Belts</a></li>
                                        <li><a href="/product/20/">Lipstick</a></li>
					</ul>
				</div>
				<div class="col-md-3">
					<h4 class="hammer5">Category</h4>
					<ul class="info">
						<li><a href="/product/18/">Flats & Sandals</a></li>
						<li><a href="/product/17/">Wedges</a></li>
						<li><a href="/product/14/">Heels</a></li>
						<li><a href="/product/16/">Flip-Flip-Flops</a></li>
						<li><a href="/product/27/">Ballerinas</a></li>
						<li><a href="/product/15/">Shoes</a></li>
						<li><a href="/product/11/">Rings</a></li>
					</ul>
					
				</div>
			</div>
		</div>
		</div>
</div>
<!--end footer -->


</body>
<script>
$(document).ready(function() { 
$('#JiSlider').JiSlider({
auto: true,
autocontrols: true,
});
});
</script>
<script>
$(document).ready(function() { 
window.onscroll = function() {myFunction()};

var navbar = document.getElementById("navbar");
var sticky = navbar.offsetTop;

function myFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky")
  } else {
    navbar.classList.remove("sticky");
  }
}
});
</script>



				<script>
$(document).ready(function() {
$("#success-alert").hide();
$("#myWish").click(function showAlert() {
$("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
$("#success-alert").slideUp(500);
    });
  });
});
</script>

<script>
var btn = $('#buttonstore');

$(window).scroll(function() {
  if ($(window).scrollTop() > 300) {
    btn.addClass('show');
  } else {
    btn.removeClass('show');
  }
});

btn.on('click', function(e) {
  e.preventDefault();
  $('html, body').animate({scrollTop:0}, '300');
});

</script>