cart/urls.py
from django.urls import path
from . import views

app_name = "cart"


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('cart_clear/',views.cart_clear , name='cart_clear'),
   
   
    
]

coupons/urls.py
from django.conf.urls import url
from django.utils.translation import gettext_lazy as _
from . import views

urlpatterns = [
    url(
        regex=_(r'^apply/$'),
        view=views.coupon_apply,
        name='apply'
    ),
]

fabtrendapp/urls.py
from django.urls import path
from fabtrendapp import views
from django.contrib.auth import views as auth_views
app_name = "fabtrendapp"

urlpatterns = [

    path('', views.indexpageView.as_view(), name='index'),
    path('base/', views.basepageView.as_view()),
    path('contact/', views.contactpageView.as_view(), name='contact'),
    path('checkout/', views.checkoutpageView.as_view(), name='checkout'),
    path('privacy/', views.privacypageView.as_view(), name='privacy'),
    path('addproduct/', views.addproductpageview.as_view()),
    path('FAQs/', views.FAQspageView.as_view(), name='faqs'),
    path('about/', views.aboutpageView.as_view(), name='about'),
    path('delete/<int:id>', views.destroy),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('insert/', views.insert),
    path('list/', views.listView.as_view()),
    path('product/', views.product, name='product'),
    path('search/', views.search, name='search'),
    path('email_success/', views.email_success, name='email_success'),
    path('category/', views.CategoryListView.as_view(), name='categorylist'),
    path('subcategory/', views.SubcategoryListView.as_view(), name='subcategorylist'),
    path('product/', views.productpageView.as_view()),
    path('product/<int:cat>/', views.show),
    path('insertproduct/', views.insertproduct,name="insertproduct"),
    path('products/<int:myid>', views.productView, name="productView"),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('query/', views.querypageview.as_view(),name='query'),
    path('feedback',views.Feedbackpageview.as_view(),name="feedback"),
	path('insertfeedback',views.feedback),
    path('feedbacks/',views.FeedbacklistView.as_view(),name="feedbacks"),
    path('insertquery/',views.insertquery),
    path('home/',views. account_home_page, name='account-home'),
    path('all_products/', views.all_products , name='all_products'),
]

fabtrendshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers, serializers, viewsets


urlpatterns = [
                path('admin/', admin.site.urls),
                path('', include('fabtrendapp.urls')),
                path('cart/', include('cart.urls')),
                path('orders/', include('orders.urls')),
                path('paytm/', include(('paytm.urls','paytm'),namespace='paytm')),
                path('coupons/', include(('coupons.urls','coupons'),namespace='coupons')),
                path('wishlists/', include(('wishlists.urls','wishlists'),namespace='wishlists')),
        ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, include
app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^created/$', views.order_created, name='order_created'),
    #url(r'^my_orders/$', views.my_orders, name='my_orders'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('refund-request/', views.RequestRefundView.as_view(), name='refund-view'),
]

cart/models.py
from django.db import models
from django.conf import settings
from fabtrendapp.models import Product


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=1)

    class Meta:
        ordering = ['-timestamp']


# Create your models here.

cart/forms.py
from django import forms
from fabtrendapp.forms import Product


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from coupons.forms import CouponApplyForm
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from fabtrendapp.models import Product
from cart.cart import Cart
from cart.forms import CartAddProductForm
from django.views.generic import TemplateView, ListView

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    coupon_apply_form = CouponApplyForm()
    cart_products = [item['product'] for item in cart]
    return render(request, 'detail.html', {'cart': cart,'coupon_apply_form': coupon_apply_form,})

def cart_clear(request):
	cart = Cart(request)
	cart.clear()
	return redirect('cart:cart_detail')

cart/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
     {% trans "Cart" %}
{% endblock %}

{% block content %}
<div class="row" style="background:rgba(230, 232, 230,0.4);">
 {% if cart|length > 0 %}
	
<div class="row" id="cart1">
		<div class="container">
        <h2 id="cart2"> Shopping Cart
            <span class="badge pull-right" id="cart3">
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                            {{ total_items }} item {{ total_items|pluralize }}, Rs. {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
		<br>
	
		<div style="background:white;">
            <table class="table table-hover">
                <thead style="font-family:Arial Rounded MT;color:black;text-align:center;font-size:18px;">
		         <tr style="font-color:white; text-align:center;left:20px;">
                        <th>Image</th>
                        <th>Product Name</th>
                        <th>Quantity</th>
						<th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                 
                                    <img src="/media/{{ product.image}}" alt="..." style="height:120px; width:100px; margin-left:20px">
                                 
                            </td>
                            <td><div id="cart4">{{ product.name }}</div></td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td id="cart5">
							
                                <a href="{% url "cart:cart_remove" product.id %}"><p style="color:white;text-decoration:none;outline:none;background:rgb(53,158,128);padding:5px;text-align:center;border-radius:5px;">Delete</p></a>
                                
                            </td>
							
                            <td id="cart6">Rs. {{ item.price }}</td>
                            <td id="cart6">Rs. {{ item.total_price }}</td>
                        </tr>
						<tr>
                   
				
                    {% endwith %}
                {% endfor %}
				 {% if cart.coupon %}
             <td id="cart8"><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num" id="cart8"><b>Rs. {{ cart.get_total_price|floatformat:"0" }}</b></td>
					
                </tr>
            <tr>
                {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
                    <td id="cart8">"{{ code }}" coupon ({{ discount }}% off)</td>
                {% endblocktrans %}
                <td colspan="4"></td>
                <td class="num neg" id="cart8">
                - Rs. {{ cart.get_discount|floatformat:"0" }}
                </td>
            </tr>
        {% endif %}
        <tr class="total">
            <td id="cart8">{% trans " Grand Total" %}</td>
            <td colspan="4"></td>
            <td class="num" id="cart8">
            Rs. {{ cart.get_total_price_after_discount|floatformat:"0" }}
            </td>
        </tr>
               
		
      </tbody>
    </table>
	</div>
			<div class="row">
			<div class="container">
    <form action="{% url "coupons:apply" %}" method="post">
        {{ coupon_apply_form}}
        <input type="submit" value="{% trans "Apply" %}">
        {% csrf_token %}
    </form>
        <p class="text-right" id="cartbutton1" style="">
            <a href="{% url "fabtrendapp:index" %}" class="btn btn-info" id="cartbutton1">Continue Shopping</a>
			 <a href="{% url "orders:order_create" %}" class="btn btn-info"  id="cartbutton1">Checkout</a>
			  <a onclick="return confirm('Dear Customer! Are You Sure You want to clear Your Cart Items')" class="clearcart btn btn-info" href="{% url "cart:cart_clear"  %}">Clear cart</a>
         </p>
        </div>
        </div>
    </div>
    </div>

	{% else %}
            <div class="col-md-4 col-md-offset-4" style="margin-top:40px;margin-bottom:40px;">
                <div class="text-center mx-md-auto">
                    <i class="fas fa-cart-arrow-down h1" style="color:rgb(58,151,128); border:1px solid rgb(58,151,128); padding:20px; border-radius:40px;"></i>
                </div>
                <div class="text-center">
                    <h3 class="pb-4">Your Cart is Currently Empty.</h3>
                    <p class="text-center pb-2">Before proceed to checkout<br> you must add some products to your shopping
                        cart.<br> You will find a lot of interesting products on our "Products" page.</p>
                    <a href="{% url 'fabtrendapp:index' %}" class="btn btn-primary px-5">Start Shopping</a>
                </div>
            </div>
        
		{% endif %}
		<br>
    </div>
                    
					
{% endblock %}